### ISSUE TITLE
Compatibility with ember-i18n

### ISSUE THREAD

**Issue by IAmJulianAcosta** [phrase/ember-cli-phraseapp#1]
I'm trying to use the plugin with `ember-i18n` (new version of `ember-cli-i18n`), but it seems that isn't compatible. I followed the blog post instructions but I can't get any translations showing in in-context-editor

**Comment by sacry-dyn** [comment]
Hi @IAmJulianAcosta sorry for the very late reply on this. Is this point still open or did you manage to set it up? If not, can you elaborate on the points that are not working?

**Comment by sacry-dyn** [comment]
I will close this for now. If need arises feel free to reopen or file a new issue.
