### ISSUE TITLE
Adaptor for ember-intl or ember-i18n

### ISSUE THREAD

**Issue by alienspaces** [phrase/ember-cli-phraseapp#3]
Hello, 

Here is an adaptor I threw together for ember-intl support.

https://github.com/alienspaces/ember-intl-phraseapp

Feel free to grab it, change it, make it yours.

Thanks!

**Comment by sacry-dyn** [comment]
Hey, sorry for letting you wait on this. Thank you for your contribution! Do you want to maintain it yourself or should we consider taking it into our codebase? :)

**Comment by FRSgit** [comment]
Closing this, as 6 years have passed and we've decided to stop maintaining emberjs integration
